### ISSUE TITLE
Dear competitors

### ISSUE THREAD

**Issue by fsmMLK** [hhu-machine-learning/hdc2021-psfnn#1]
I noticed you did not create a release yet. Please remember to create one before the deadline. See the instructions on the Rules.

**Comment by 99991** [comment]
Thank you for the reminder! There should be a release now.

https://github.com/hhu-machine-learning/hdc2021-psfnn/releases

Previously, the code simply was not quite ready yet. Sorry for the late submission!

**Comment by fsmMLK** [comment]
what python version are you using?

**Comment by 99991** [comment]
Python 3.9.1 definitely works, but earlier versions (3.8, possibly 3.7) might work as well. We use f-strings, so version 3.6 is a lower bound.

Unfortunately I can not check the exact version of the system where we can most of the experiments due to a network outage, but I'll come back to this once it is up again.

Are you seeing any errors with your Python version?

**Comment by fsmMLK** [comment]
no problems so far. I am installing now the requirements to execute your code.

**Comment by 99991** [comment]
Great to hear! I could get access to our system again and the Python version there was 3.7.3, but you can probably stay with 3.9.1 if you already started installing requirements. I would be surprised if there is a difference between those two versions.

**Comment by fsmMLK** [comment]
it seems there is no compatible version of opencv with the latest versions of the other modules. I will have to try python 3.7.

Can you generate a requirements.txt using pip? or an environment.yml using conda?

**Comment by 99991** [comment]
`pipreqs` generates the following for Python 3.9.1 (on Windows):

```
opencv_contrib_python==4.5.2.54
pytesseract==0.3.8
numpy==1.20.3
fuzzywuzzy==0.18.0
scipy==1.7.0
torch==1.9.0+cu111
matplotlib==3.4.2
Pillow==8.4.0
```

(I removed the lines `net==0.1` and `util==0.0.1` since they seemed incorrect)

For Python 3.7.3 running on Debian 10, the library versions currently are:

```
numpy==1.16.2
fuzzywuzzy==0.18.0
scipy==1.4.1
pytesseract==0.3.7
torch==1.8.1+cu111
matplotlib==3.3.1
opencv_python==4.4.0.42
Pillow==8.4.0
```

Another option (untested): If you do not want to train the networks yourself, you might even get away with not installing opencv and removing `import cv2` in https://github.com/hhu-machine-learning/hdc2021-psfnn/blob/c729b63ea65c5d597b5c4c49264b28df0429293f/train/networks/transforms.py#L4

**Comment by fsmMLK** [comment]
I think it is working now.

**Comment by fsmMLK** [comment]
I found a problem. The links https://asdf10.com/blur_train_step_{step}_batch_50000.pth
for steps 11 and 12 do not exist. I did not try for steps>12.

links for steps<=10 work fine.

**Comment by 99991** [comment]
That is correct. It is unlikely that our method could pass higher steps on the test dataset since it just barely passed steps 10 and 11 on the public training dataset. https://github.com/hhu-machine-learning/hdc2021-psfnn#ocr-scores We should probably throw a more verbose exception if a higher step is requested.

**Comment by fsmMLK** [comment]
can I assume then that your method stops at step 11?

**Comment by 99991** [comment]
Yes. (I believe we wrote at the same time, so the previous answer might not have shown up.)

**Comment by fsmMLK** [comment]
Can you make the repository public? Tks.

**Comment by 99991** [comment]
Of course! The repository is now public.
